export const category = [
    {
      link: "/education",
      text: "Образование",
      pid: "home",
      subcat: [
        {
          link: "/preschoolers",
          text: "Дошкольники",
          pid: "home",
          items: [
            { link: "/kindergartens", text: "Детские сады", pid: "home" },
            { link: "/privatekindergartens", text: "Частные детские сады и присмотр", pid: "home" },
            { link: "/forschool", text: "Подготовка к школе", pid: "home" },
            { link: "/development", text: "Развивающие занятия", pid: "home" },
            { link: "/speechtherapist", text: "Логопеды и дефектологи", pid: "home" },
            { link: "/language", text: "Иностранные языки", pid: "home" },
          ],
        },
        {
          link: "/schoolers",
          text: "Школьники",
          pid: "home",
          items: [
            { link: "/tutor", text: "Репетиторы и курсы подготовки к ЕГЭ и ОГЭ", pid: "home" },
            { link: "/schools", text: "Школы и гимназии", pid: "home" },
            { link: "/private-schools", text: "Частные школы", pid: "home" },
            { link: "/internats", text: "Школы-интернаты", pid: "home" },
            { link: "/sunday-schools", text: "Воскресные школы, духовные учебные заведения для детей", pid: "home" },
            { link: "/secondary-specialized-education", text: "Среднее специальное образование (Лицеи, колледжи и техникумы, ПТУ, училища)", pid: "home" },
            { link: "/higher-education", text: "Высшее образование (Институты, вузы, университеты)", pid: "home" },
            { link: "/military-academies-and-schools", text: "Военные академии и училища", pid: "home" },
            { link: "/conservatories-and-music-universities", text: "Консерватории и музыкальные вузы", pid: "home" },
            { link: "/choreographic-schools", text: "Хореографические училища", pid: "home" },
          ],
        },
        {
          link: "/addeducation",
          text: "Дополнительное образование",
          pid: "home",
          items: [
            { link: "/dopobr", text: "Учебные центры доп. образования", pid: "home" },
            { link: "/language-school", text: "Языковые школы и курсы иностранных языков", pid: "home" },
            { link: "/it", text: "IT - школы и курсы информатики и программирования", pid: "home" },
            { link: "/upquals", text: "Профессиональная подготовка и повышение квалификации", pid: "home" },
            { link: "/busines-drive", text: "Школы управления бизнесом и автошколы", pid: "home" },
    
          ],
        },
      ],
    },
    {
        link: "/shop-child",
        text: "Магазины детские",
        pid: "home",
        items: [
            {text: "Детские супермаркеты", pid: "home" },
            {text: "Детские интернет-магазины", pid: "home" },
            {text: "Детские магазины одежды (головные уборы)", pid: "home" },
            {text: "Магазины детской обуви", pid: "home" },
            {text: "Ортопедические магазины", pid: "home" },
            {text: "Игрушки и игры", pid: "home" },
            {text: "Канцелярские и книжные магазины (учебники)", pid: "home" },
            {text: "Магазины творчества и рукоделия", pid: "home" },
            {text: "Спортивные, музыкальные и узкопрофильные магазины", pid: "home" },
            {text: "Магазины детской мебели", pid: "home" },
            {text: "Ювелирные магазины и магазины бижутерии для детей", pid: "home" }
          ],
        
      },
    
     
      {
          link: "/cas",
          text: "Кружки и секции",
          pid: "home",
          items: [
              { text: "Дома культуры и детского творчества", pid: "home" },
              {text: "Спорткомплексы и тренировочные базы (стадионы)", pid: "home" },
              {text: "Пение и Музыкальные школы (вокал)", pid: "home" },
              {text: "Танцы и хореография", pid: "home" },
              {text: "Рисование и Художественные школы", pid: "home" },
              {text: "Аэробика и фитнес для детей (йога)", pid: "home" },
              {text: "Бассейны и Дайвинг-клубы", pid: "home" },
              {text: "Борьба и боевые искусства", pid: "home" },
              {text: "Театральные кружки", pid: "home" },
              {text: "Шахматы", pid: "home" },
              {text: "Клубы робототехники и конструирования", pid: "home" },
              {text: "Другие кружки (Фотошколы, картинг, модельные школы)", pid: "home" },
              {text: "Секции бесплатные и по сертификату", pid: "home" },
              {text: "Молодежные и общественные организации", pid: "home" },
            ],
          
        },
        {
            link: "/eat",
            text: "Еда и продукты",
            pid: "home",
            items: [
                { text: "Рецепты", pid: "home" },
                {text: "Магазины безглютеновых и безлактозных продуктов", pid: "home" },
                {text: "Фермерские и эко-продукты", pid: "home" },
                {text: "Магазины детского питания", pid: "home" },
                {text: "Доставка еды (для мам, детей и пр.)", pid: "home" },
                {text: "Кафе с детской комнатой", pid: "home" },
                
              ],
            
          },
          {
            link: "/holidays",
            text: "Праздники",
            pid: "home",
            items: [
                { text: "Магазины товаров для детского праздника (украшения)", pid: "home" },
                {text: "Пакетные предложения", pid: "home" },
                {text: "Аниматоры", pid: "home" },
                {text: "Игровые центры", pid: "home" },
                {text: "Детские кафе", pid: "home" },
                {text: "Торты и десерты", pid: "home" },
                {text: "Воздушные шары", pid: "home" },
                {text: "Детские карнавальные, танцевальные и театральные костюмы", pid: "home" },
                {text: "Фотографы и видеографы", pid: "home" },
                {text: "Кейтеринг (доставка еды)", pid: "home" },
                {text: "Мастер-классы и квесты", pid: "home" },
                {text: "Аренда помещений", pid: "home" },
                {text: "Аренда товаров для праздника (батуты, шоколадные фонтаны)", pid: "home" },
            ],
            
          },
          {
            link: "/services",
            text: "Услуги для детей",
            pid: "home",
            items: [
                { text: "Детские лагеря, санатории (дома отдыха, турбазы)", pid: "home" },
                {text: "Детские фотостудии", pid: "home" },
                {text: "Парикмахерские и салоны красоты для детей", pid: "home" },
                {text: "Оптика", pid: "home" },
            ],
            
          },
          {
            link: "/entertaiment",
            text: "Развлечения",
            pid: "home",
            items: [
                { text: "Парки аттракционов и отдыха", pid: "home" },
                {text: "Зоопарки, фермы и заповедники", pid: "home" },
                {text: "Кинотеатры и театры", pid: "home" },
                {text: "Детские выставки и музеи", pid: "home" },
                { text: "Цирк и концерты", pid: "home" },
                {text: "Детские экскурсии", pid: "home" },
                {text: "Игровые и батутные центры", pid: "home" },
                {text: "Мастер-классы, квесты и шоу", pid: "home" },
                { text: "Аквапарки", pid: "home" },
                {text: "Каток", pid: "home" },
                {text: "Бильярдные и боулинг-клубы", pid: "home" },
                {text: "Картинг и конные клубы", pid: "home" },
                { text: "Лазертаг и пейнтбольные клубы", pid: "home" },
                {text: "Теннисные клубы", pid: "home" },
                {text: "Скалодромы и веревочные парки", pid: "home" },
                {text: "Пункты проката (лодки, велосипеды и пр.)", pid: "home" },
                {text: "Кафе", pid: "home" },
            ],
            
          },
          {
            link: "/heals",
            text: "Здоровье",
            pid: "home",
            items: [
                { text: "Врач на дом", pid: "home" },
                {text: "Детская скорая помощь", pid: "home" },
                {text: "Детские травмпункты", pid: "home" },
                {text: "Детские больницы", pid: "home" },
                { text: "Детские поликлиники", pid: "home" },
                {text: "Медицинские центры", pid: "home" },
                {text: "Детские диагностические центры", pid: "home" },
                {text: "Диспансеры и лаборатории", pid: "home" },
                { text: "Реабилитационные центры и санатории (оздоровительные центры)", pid: "home" },
                {text: "Логопеды и коррекция речи", pid: "home" },
                {text: "Массаж для детей", pid: "home" },
                {text: "Стоматология", pid: "home" },
                { text: "Ортопедия", pid: "home" },
                {text: "Офтальмология", pid: "home" },
                {text: "Неврологи", pid: "home" },
                {text: "Процедурный кабинет или медсестра на дом", pid: "home" },
                {text: "Аптеки и аптеки онлайн", pid: "home" },
            ],
            
          },
          {
            link: "/mom",
            text: "Мама и малыш",
            pid: "home",
            items: [
                { text: "Центры планирования беременности", pid: "home" },
                {text: "Ведение беременности и родов", pid: "home" },
                {text: "Перинатальные центры и Роддома", pid: "home" },
                {text: "Курсы для беременных", pid: "home" },
                { text: "Магазины для беременных", pid: "home" },
                {text: "Няни и центры присмотра", pid: "home" },
                {text: "Грудничковое плавание и фитнес", pid: "home" },
                {text: "Специалисты по кормлению и здоровью (массаж)", pid: "home" },
                { text: "Аренда игрушек и детских товаров", pid: "home" },
            ],
            
          },
          {
            link: "/gos",
            text: "Гос учреждения и соц помощь",
            pid: "home",
            items: [
                { text: "Загсы", pid: "home" },
                {text: "Детские дома и приюты", pid: "home" },
                {text: "Центры соцподдержки и соцзащиты", pid: "home" },
                {text: "Службы ПДН", pid: "home" },
                { text: "Центры психологической помощи и ПМПК", pid: "home" },
            ],
            
          },
  ];
  