import BreadcrumbDinamic from "@/components/Breadcrumb/Breadcrumb.jsx";
import styles from "@/styles/Catalog.module.scss";

import NewsCard from "@/components/ChapterCard/NewsCard.jsx";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import Head from "next/head";
import { useRouter } from "next/router.js";

export default function News({ data }) {
  const router = useRouter();

  const { asPath } = router;
  const path = asPath.split("?")[0];
  return (
    <div>
      <Head>
        <title>Новости</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.contentWrapper}>
        <Header />
        <main className={styles.catalogWrapper}>
          <div className={styles.breadCrumb}>
            <BreadcrumbDinamic />
          </div>
          <h2 className={styles.title}>НОВОСТИ</h2>
          <div className={styles.cardWrapper}>
            {data.map((el) => {
              return (
                <NewsCard
                  key={el[0]}
                  src={`https://volga24bot.com/cgi-bin/news/photos/${el[0]}/logo.png`}
                  text={el[1]}
                  date={el[3]}
                  link={`${path}/${el[0]}?name=${el[1]}`}
                />
              );
            })}
          </div>
        </main>
        <Footer />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://volga24bot.com/cgi-bin/news/getAllNews.php`);

  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
